from flask import Flask,render_template,request,redirect,session,flash,url_for,jsonify,make_response
import config
import mysql.connector
from flask_mail import Mail, Message
import bcrypt
import random
import os
from werkzeug.utils import secure_filename
import uuid
import traceback
from utils.pdf_generator import generate_pdf
from itsdangerous import URLSafeTimedSerializer,SignatureExpired, BadSignature
import secrets
import re



import razorpay
razorpay_client = razorpay.Client(
    auth=(config.RAZORPAY_KEY_ID, config.RAZORPAY_KEY_SECRET)
)


app = Flask(__name__)

app.secret_key = config.SECRET_KEY
serializer = URLSafeTimedSerializer(app.secret_key)


app.config['MAIL_SERVER'] = config.MAIL_SERVER
app.config['MAIL_PORT'] = config.MAIL_PORT
app.config['MAIL_USE_TLS'] = config.MAIL_USE_TLS
app.config['MAIL_USERNAME'] = config.MAIL_USERNAME
app.config['MAIL_PASSWORD'] = config.MAIL_PASSWORD

mail = Mail(app)


# -------------------------------
# MySQL Database Connection Setup
# -------------------------------
def get_db_connection():

    
    conn = mysql.connector.connect(
        host=config.DB_HOST,
        user=config.DB_USER,
        password=config.DB_PASSWORD,
        database=config.DB_NAME
    )
    return conn



# --------------------------------
# Home Route (First Flask Route)
# --------------------------------

@app.route("/")
def home():
    return render_template("home.html")

password = "admin123"
hashed = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())
print(hashed.decode('utf-8'))

@app.route('/admin-signup', methods=['GET','POST'])
def admin_signup():  

    if request.method == 'GET':
        return render_template('admin/admin_signup.html')

    name = request.form['name']
    email = request.form['email']

    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT id FROM admin WHERE email = %s', (email,))
    existing_email = cursor.fetchone()
    cursor.close()
    conn.close()

    if existing_email:
        flash("Email already registered. Please login.", "danger")
        return redirect(url_for('admin_signup'))

    session['temp_name'] = name
    session['temp_email'] = email

    otp = secrets.randbelow(900000) + 100000
    session['otp'] = otp

    message = Message(
        subject="SmartCart Admin OTP",
        sender=config.MAIL_USERNAME,
        recipients=[email]
    )
    message.body = f"OTP: {otp}"
    mail.send(message)

    flash("OTP sent to your email", "success")
    return redirect(url_for('verify_otp_page'))
# route for the verify otp

@app.route('/verify-otp-page')
def verify_otp_page():
    if 'otp' not in session:
        return redirect(url_for('admin_signup'))
    return render_template('admin/verify.html')

@app.route('/verify-otp',methods = ['POST'])
def verify_otp_post():
    user_otp = request.form['otp']
    password = request.form['password']

    # compare the user entered otp and otp generated by the server that is in session

    stored_otp = session.get('otp')
    name = session.get('temp_name')
    email = session.get('temp_email')

    if not stored_otp or not name or not email:
        flash("Session expired. Please try again.", "danger")
        return redirect(url_for('admin_signup'))

    if str(stored_otp) != str(user_otp):
       flash("Invalid OTP. Try again.", "danger")
       return redirect(url_for('verify_otp_page'))
    
    #  if the otps are matched then create a hashed password using bcrypt

    hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

    # Next step insert the admin into the database

    conn  = get_db_connection()
    cursor = conn.cursor()
    cursor.execute(
"INSERT INTO admin(name,email,password,profile_image,is_approved) VALUES(%s,%s,%s,%s,%s)",
(name, email, hashed_password, 'default.png', False))
    conn.commit()
    cursor.close()
    conn.close()

    # Next step is to clear the temporary data in session
    session.pop('otp',None)
    session.pop('temp_name', None)
    session.pop('temp_email', None)

    flash("Registered successfully! Wait for admin approval.", "success")
    return redirect(url_for('admin_login'))

# admin login route
@app.route('/admin-login', methods=['GET','POST'])
def admin_login():

    if request.method == 'GET':
        return render_template('/admin/admin_login.html')
    
    email = request.form['email']
    password = request.form['password']

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    cursor.execute("SELECT * FROM admin WHERE email = %s", (email,))
    admin = cursor.fetchone()
    cursor.close()
    conn.close()

    # ❌ Email not found
    if not admin:
        flash("Email not found! Please register.", "danger")
        return redirect(url_for('admin_signup'))
    
    # 🔐 Password check
    stored_hashed_password = admin['password']

    if isinstance(stored_hashed_password, str):
        stored_hashed_password = stored_hashed_password.encode('utf-8')

    if not bcrypt.checkpw(password.encode('utf-8'), stored_hashed_password):
        flash("Incorrect Password! Try Again", "danger")
        return redirect(url_for('admin_login'))
    
    # 🔒 Approval check
    if not admin.get('is_approved', False):
        flash("Your account is pending approval by Super Admin.", "danger")
        return redirect(url_for('admin_login'))
    
    # ✅ Session
    session['admin_id'] = admin['id']
    session['admin_name'] = admin['name']
    session['admin_email'] = admin['email']
    session['admin_role'] = admin['role'] if admin.get('role') else 'admin'
    session['admin_profile'] = admin['profile_image'] if admin.get('profile_image') else 'default.png'
    

    flash("Login Successful.", "success")
    return redirect(url_for('dashboard'))

# This is forgot password for admin and user
@app.route('/forgot-password/<role>', methods=['GET', 'POST'])
def forgot_password(role):

    if role not in ['user', 'admin']:
        return "Invalid role", 400

    if request.method == 'GET':
        return render_template(f'{role}/forgot_password.html', role=role)

    email = request.form['email']

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    if role == 'user':
        cursor.execute("SELECT * FROM users WHERE email=%s", (email,))
    else:
        cursor.execute("SELECT * FROM admin WHERE email=%s", (email,))

    account = cursor.fetchone()

    cursor.close()
    conn.close()

    # 🔐 Prevent email enumeration
    if not account:
        flash("If the email exists, a reset link has been sent.", "info")
        return redirect(url_for('user_login' if role == 'user' else 'admin_login'))

    # 🔐 Generate token
    token = serializer.dumps(email, salt='password-reset-salt')

    reset_link = url_for('reset_password', role=role, token=token, _external=True)

    msg = Message(
        subject="Reset Your Password",
        sender=app.config['MAIL_USERNAME'],
        recipients=[email]
    )

    msg.body = f"""
Hi,

Click the link below to reset your password:

{reset_link}

This link will expire in 10 minutes.
"""

    # ✅ EMAIL SENDING WITH ERROR HANDLING
    try:
        mail.send(msg)
    except Exception as e:
        print("Mail error:", e)
        flash("Unable to send email. Try again later.", "danger")
        return redirect(request.url)

    # ✅ SUCCESS FLOW
    flash("If the email exists, a reset link has been sent.", "info")

    login_route = 'user_login' if role == 'user' else 'admin_login'
    return redirect(url_for(login_route))

# Reset link route 
@app.route('/reset-password/<role>/<token>', methods=['GET', 'POST'])
def reset_password(role, token):

    # ✅ Validate role
    if role not in ['user', 'admin']:
        return "Invalid role", 400

    # 🔐 Validate token
    try:
        email = serializer.loads(token, salt='password-reset-salt', max_age=600)
    except SignatureExpired:
        flash("Reset link expired!", "danger")
        return redirect(url_for('forgot_password', role=role))
    except BadSignature:
        flash("Invalid reset link!", "danger")
        return redirect(url_for('forgot_password', role=role))

    # ✅ Show reset page
    if request.method == 'GET':
        return render_template(f'{role}/reset_password.html', role=role)

    # 🔐 Get new password
    new_password = request.form['password']
    confirm_password = request.form.get('confirm_password')

    # ✅ Validate password
    if new_password != confirm_password:
        flash("Passwords do not match!", "danger")
        return redirect(request.url)

    if len(new_password) < 6:
        flash("Password must be at least 6 characters!", "danger")
        return redirect(request.url)

    # 🔐 Hash password
    hashed_password = bcrypt.hashpw(new_password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

    conn = get_db_connection()
    cursor = conn.cursor()

    if role == 'user':
     cursor.execute(
        "UPDATE users SET password=%s WHERE email=%s",
        (hashed_password, email)
    )
    else:
     cursor.execute(
        "UPDATE admin SET password=%s WHERE email=%s",
        (hashed_password, email)
    )

    conn.commit()

    cursor.close()
    conn.close()

    flash("Password reset successful!", "success")

    return redirect(url_for('user_login' if role == 'user' else 'admin_login'))

@app.route('/admin-dashboard')
def dashboard():

    if 'admin_id' not in session:
        flash("Please login first!", "danger")
        return redirect(url_for('admin_login'))
    
    admin_id = session['admin_id']

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    # 📦 Total Products
    cursor.execute(
        "SELECT COUNT(*) AS total_products FROM products WHERE admin_id = %s",
        (admin_id,)
    )
    total_products = cursor.fetchone()['total_products']

    # 👥 Total Users (global - fine)
    cursor.execute("SELECT COUNT(*) AS total_users FROM users")
    total_users = cursor.fetchone()['total_users']

    # 🧾 Total Orders
    # 🧾 Total Orders (OPTIMIZED)
    cursor.execute("""
SELECT COUNT(*) AS total_orders
FROM orders o
JOIN products p ON o.product_id = p.product_id
WHERE p.admin_id = %s
""", (admin_id,))

    total_orders = cursor.fetchone()['total_orders']

    # 💰 Total Revenue
    cursor.execute("""
SELECT SUM(o.amount) AS revenue
FROM orders o
JOIN products p ON o.product_id = p.product_id
WHERE p.admin_id = %s
""", (admin_id,))
    revenue = cursor.fetchone()['revenue'] or 0   # ✅ REQUIRED

    # 🔥 Recent Orders
    cursor.execute("""
        SELECT * FROM orders 
        WHERE product_id IN (
            SELECT product_id FROM products WHERE admin_id = %s
        )
        ORDER BY created_at DESC
        LIMIT 5
    """, (admin_id,))
    recent_orders = cursor.fetchall()   # ✅ FIX

    cursor.close()
    conn.close()

    return render_template(
        'admin/dashboard.html',
        admin_name=session['admin_name'],
        total_products=total_products,
        total_users=total_users,
        total_orders=total_orders,
        revenue=revenue,
        recent_orders=recent_orders
    )
    
def is_super_admin():
    return session.get('admin_role') == 'super_admin'

@app.route('/super-admin/pending-admins')
def pending_admins():

    if 'admin_id' not in session or not is_super_admin():
        flash("Unauthorized access!", "danger")
        return redirect(url_for('admin_login'))

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute("SELECT id, name, email FROM admin WHERE is_approved = 0")
    admins = cursor.fetchall()

    cursor.close()
    conn.close()

    return render_template("admin/pending_admins.html", admins=admins)

@app.route('/super-admin/approve/<int:admin_id>', methods=['POST'])
def approve_admin(admin_id):

    if 'admin_id' not in session or not is_super_admin():
        return jsonify({'status': 'error', 'message': 'Unauthorized'}), 403

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    # 🔥 GET ADMIN EMAIL
    cursor.execute("SELECT email, name FROM admin WHERE id=%s", (admin_id,))
    admin = cursor.fetchone()

    if not admin:
        return jsonify({'status': 'error', 'message': 'Admin not found'})

    # 🔥 UPDATE STATUS
    cursor.execute("UPDATE admin SET is_approved = 1 WHERE id=%s", (admin_id,))
    conn.commit()

    # 🔥 SEND EMAIL
    try:
        msg = Message(
            subject="Admin Request Approved ✅",
            sender=app.config['MAIL_USERNAME'],
            recipients=[admin['email']]
        )

        msg.body = f"""
Hello {admin['name']},

🎉 Your admin request has been APPROVED.

You can now login and access the admin dashboard.

Regards,
SmartCart Team
"""

        mail.send(msg)

    except Exception as e:
        print("Mail error:", e)

    cursor.close()
    conn.close()

    return jsonify({'status': 'success', 'message': 'Admin approved & email sent'})
@app.route('/super-admin/reject/<int:admin_id>', methods=['POST'])
def reject_admin(admin_id):

    if 'admin_id' not in session or not is_super_admin():
        return jsonify({'status': 'error', 'message': 'Unauthorized'}), 403

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    # 🔥 GET ADMIN DETAILS BEFORE DELETE
    cursor.execute("SELECT email, name, role FROM admin WHERE id=%s", (admin_id,))
    admin = cursor.fetchone()

    if not admin:
        return jsonify({'status': 'error', 'message': 'Admin not found'})

    if admin_id == session['admin_id']:
        return jsonify({'status': 'error', 'message': 'Cannot delete yourself'})

    if admin['role'] == 'super_admin':
        return jsonify({'status': 'error', 'message': 'Cannot delete super admin'})

    # 🔥 DELETE ADMIN
    cursor.execute("DELETE FROM admin WHERE id=%s", (admin_id,))
    conn.commit()

    # 🔥 SEND EMAIL
    try:
        msg = Message(
            subject="Admin Request Rejected ❌",
            sender=app.config['MAIL_USERNAME'],
            recipients=[admin['email']]
        )

        msg.body = f"""
Hello {admin['name']},

❌ Your admin request has been REJECTED.

If you think this is a mistake, please contact support.

Regards,
SmartCart Team
"""

        mail.send(msg)

    except Exception as e:
        print("Mail error:", e)

    cursor.close()
    conn.close()

    return jsonify({'status': 'success', 'message': 'Admin rejected & email sent'})
# ------------------- IMAGE UPLOAD PATH -------------------
UPLOAD_FOLDER = 'static/uploads/product_images'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER


# =================================================================
# ROUTE 7: SHOW ADD PRODUCT PAGE (Protected Route)
# =================================================================
@app.route('/admin/add-item', methods=['GET'])
def add_item_page():

    # Only logged-in admin can access
    if 'admin_id' not in session:
        flash("Please login first!", "danger")
        return redirect('/admin-login')

    return render_template("admin/add_item.html")



# =================================================================
# ROUTE 8: ADD PRODUCT INTO DATABASE
# =================================================================
@app.route('/admin/add-item', methods=['POST'])
def add_item():

    # Check admin session
    if 'admin_id' not in session:
        flash("Please login first!", "danger")
        return redirect('/admin-login')

    # 1️⃣ Get form data
    name = request.form['name']
    description = request.form['description']
    category = request.form['category']
    price = request.form['price']
    image_file = request.files['image']

    # 2️⃣ Validate image upload
    if image_file.filename == "":
        flash("Please upload a product image!", "danger")
        return redirect('/admin/add-item')

    # 3️⃣ Secure the file name
    filename = str(uuid.uuid4()) + "_" + secure_filename(image_file.filename)

    # 4️⃣ Create full path
    image_path = os.path.join(app.config['UPLOAD_FOLDER'], filename)

    # 5️⃣ Save image into folder
    image_file.save(image_path)

    # 6️⃣ Insert product into database
    conn = get_db_connection()
    cursor = conn.cursor()
    admin_id=session['admin_id']

    cursor.execute(
        "INSERT INTO products (name, description, category, price, image,admin_id) VALUES (%s, %s, %s, %s, %s,%s)",
        (name, description, category, price, filename,admin_id)
    )

    conn.commit()
    cursor.close()
    conn.close()

    flash("Product added successfully!", "success")
    return redirect(url_for('dashboard'))

#=================================================================
# ROUTE 10: VIEW SINGLE PRODUCT DETAILS
# =================================================================
@app.route('/admin/view-item/<int:item_id>')
def view_item(item_id):

    if 'admin_id' not in session:
        flash("Please login first!", "danger")
        return redirect('/admin-login')

    admin_id = session['admin_id']   # ✅ get admin

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute("""
        SELECT * FROM products 
        WHERE product_id = %s AND admin_id = %s
    """, (item_id, admin_id))

    product = cursor.fetchone()

    cursor.close()
    conn.close()

    if not product:
        flash("Unauthorized access or product not found!", "danger")
        return redirect('/admin/item-list')

    return render_template("admin/view_item.html", product=product)

# Route: /admin/update-item/<id> (GET)
# =================================================================
# ROUTE 11: SHOW UPDATE FORM WITH EXISTING DATA
# =================================================================
@app.route('/admin/update-item/<int:item_id>', methods=['GET'])
def update_item_page(item_id):

    if 'admin_id' not in session:
        flash("Please login!", "danger")
        return redirect('/admin-login')

    admin_id = session['admin_id']   # ✅ get logged-in admin

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute("""
        SELECT * FROM products 
        WHERE product_id = %s AND admin_id = %s
    """, (item_id, admin_id))

    product = cursor.fetchone()

    cursor.close()
    conn.close()

    if not product:
        flash("Unauthorized access or product not found!", "danger")
        return redirect('/admin/item-list')

    return render_template("admin/update_item.html", product=product)

# 🟩 Step 2: Update Product Logic
# Route: /admin/update-item/<id> (POST)
# =================================================================
# ROUTE-12: UPDATE PRODUCT + OPTIONAL IMAGE REPLACE
# =================================================================
@app.route('/admin/update-item/<int:item_id>', methods=['POST'])
def update_item(item_id):

    if 'admin_id' not in session:
        flash("Please login!", "danger")
        return redirect('/admin-login')
    
    admin_id = session['admin_id']

    # 1️⃣ Get updated form data
    name = request.form['name']
    description = request.form['description']
    category = request.form['category']
    price = request.form['price']

    new_image = request.files['image']

    # 2️⃣ Fetch old product data
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)
    cursor.execute("SELECT * FROM products WHERE product_id = %s and admin_id = %s", (item_id,admin_id,))
    product = cursor.fetchone()

    if not product:
        flash("Product not found!", "danger")
        return redirect('/admin/item-list')

    old_image_name = product['image']

    # 3️⃣ If admin uploaded a new image → replace it
    if new_image and new_image.filename != "":
        
        # Secure filename
        from werkzeug.utils import secure_filename
        new_filename = secure_filename(new_image.filename)

        # Save new image
        new_image_path = os.path.join(app.config['UPLOAD_FOLDER'], new_filename)
        new_image.save(new_image_path)

        # Delete old image file
        old_image_path = os.path.join(app.config['UPLOAD_FOLDER'], old_image_name)
        if os.path.exists(old_image_path):
            os.remove(old_image_path)

        final_image_name = new_filename

    else:
        # No new image uploaded → keep old one
        final_image_name = old_image_name

    # 4️⃣ Update product in the database
    cursor.execute("""
        UPDATE products
        SET name=%s, description=%s, category=%s, price=%s, image=%s
        WHERE product_id=%s
    """, (name, description, category, price, final_image_name, item_id))

    conn.commit()
    cursor.close()
    conn.close()

    flash("Product updated successfully!", "success")
    return redirect('/admin/item-list')

# =================================================================
# UPDATED PRODUCT LIST WITH SEARCH + CATEGORY FILTER
# =================================================================
@app.route('/admin/item-list')
def item_list():

    if 'admin_id' not in session:
        flash("Please login!", "danger")
        return redirect('/admin-login')

    search = request.args.get('search', '')
    category_filter = request.args.get('category', '')

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    # 1️⃣ Fetch category list for dropdown
    cursor.execute("SELECT DISTINCT category FROM products")
    categories = cursor.fetchall()

    # 2️⃣ Build dynamic query based on filters
    query = "SELECT * FROM products WHERE 1=1"
    params = []

    if search:
        query += " AND name LIKE %s"
        params.append("%" + search + "%")

    if category_filter:
        query += " AND category = %s"
        params.append(category_filter)

    cursor.execute(query, params)
    products = cursor.fetchall()

    cursor.close()
    conn.close()

    return render_template(
        "admin/item_list.html",
        products=products,
        categories=categories
    )

# ⭐ ROUTE 2: Delete Product + Delete Image from Server
# =================================================================
# DELETE PRODUCT (DELETE DB ROW + DELETE IMAGE FILE)
# =================================================================
@app.route('/admin/delete-item/<int:item_id>')
def delete_item(item_id):

    if 'admin_id' not in session:
        flash("Please login first!", "danger")
        return redirect('/admin-login')

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    # 1️⃣ Fetch product to get image name
    cursor.execute("SELECT image FROM products WHERE product_id=%s", (item_id,))
    product = cursor.fetchone()

    if not product:
        flash("Product not found!", "danger")
        return redirect('/admin/item-list')

    image_name = product['image']

    # Delete image from folder
    image_path = os.path.join(app.config['UPLOAD_FOLDER'], image_name)
    if os.path.exists(image_path):
        os.remove(image_path)

    # 2️⃣ Delete product from DB
    cursor.execute("DELETE FROM products WHERE product_id=%s", (item_id,))
    conn.commit()

    cursor.close()
    conn.close()

    flash("Product deleted successfully!", "success")
    return redirect('/admin/item-list')


ADMIN_UPLOAD_FOLDER = 'static/uploads/admin_profiles'
app.config['ADMIN_UPLOAD_FOLDER'] = 'static/uploads/admin_profiles'

# =================================================================
# ROUTE 1: SHOW ADMIN PROFILE DATA
# =================================================================


from flask import request, redirect, session, render_template, flash
from werkzeug.utils import secure_filename
import os
import uuid

@app.route('/user/profile', methods=['GET', 'POST'])
def user_profile():

    # 🔒 Check login
    if 'user_id' not in session:
        return redirect('/user-login')

    user_id = session['user_id']

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    # ============================
    # 🔥 HANDLE POST (UPDATE PROFILE)
    # ============================
    if request.method == 'POST':

        # 🔹 Get form data
        name = request.form.get('name')
        phone = request.form.get('phone')
        address = request.form.get('address')
        city = request.form.get('city')

        # 🔹 Get image
        image = request.files.get('profile_image')

        # 🔹 Upload folder
        upload_folder = os.path.join('static', 'uploads', 'profile')
        os.makedirs(upload_folder, exist_ok=True)

        # ============================
        # 🔥 IF IMAGE UPLOADED
        # ============================
        if image and image.filename != "":

            # ✅ Unique filename (important)
            filename = str(uuid.uuid4()) + "_" + secure_filename(image.filename)

            upload_path = os.path.join(upload_folder, filename)
            image.save(upload_path)

            # 🔹 Update with image
            cursor.execute("""
                UPDATE users 
                SET name=%s, phone=%s, address=%s, city=%s, image=%s
                WHERE user_id=%s
            """, (name, phone, address, city, filename, user_id))

        # ============================
        # 🔥 NO IMAGE UPLOADED
        # ============================
        else:
            cursor.execute("""
                UPDATE users 
                SET name=%s, phone=%s, address=%s, city=%s
                WHERE user_id=%s
            """, (name, phone, address, city, user_id))

        conn.commit()

        flash("Profile updated successfully!", "success")
        return redirect('/user/profile')

    # ============================
    # 🔹 GET USER DATA
    # ============================
    cursor.execute("SELECT * FROM users WHERE user_id=%s", (user_id,))
    user = cursor.fetchone()

    cursor.close()
    conn.close()

    return render_template("user/profile.html", user=user)

    
    
# =================================================================
# ROUTE 2: UPDATE ADMIN PROFILE (NAME, EMAIL, PASSWORD, IMAGE)
# =================================================================
@app.route('/admin/profile', methods=['POST'])
def admin_profile_update():

    if 'admin_id' not in session:
        flash("Please login!", "danger")
        return redirect('/admin-login')

    name = request.form.get('name')
    email = request.form.get('email')
    password = request.form.get('password')
    image = request.files.get('profile_image')

    conn = get_db_connection()
    cursor = conn.cursor()

    # 🔥 IMAGE UPLOAD
    if image and image.filename != "":
        from werkzeug.utils import secure_filename
        import os, uuid

        filename = str(uuid.uuid4()) + "_" + secure_filename(image.filename)

        upload_folder = os.path.join('static', 'uploads', 'admin_profiles')
        os.makedirs(upload_folder, exist_ok=True)

        image.save(os.path.join(upload_folder, filename))

        session['admin_profile'] = filename

        cursor.execute("""
            UPDATE admin SET name=%s, email=%s, image=%s
            WHERE admin_id=%s
        """, (name, email, filename, session['admin_id']))

    else:
        cursor.execute("""
    UPDATE admin 
    SET name=%s, email=%s
    WHERE id=%s
""", (name, email, session['admin_id']))

    # 🔐 PASSWORD UPDATE
    if password:
        import bcrypt
        hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())

        cursor.execute("""
    UPDATE admin 
    SET password=%s 
    WHERE id=%s
""", (hashed, session['admin_id']))

    conn.commit()
    cursor.close()
    conn.close()

    # 🔥 Update session
    session['admin_name'] = name
    session['admin_email'] = email

    flash("Profile updated successfully!", "success")
    return redirect('/admin/profile-edit')

@app.route('/admin/profile-edit', methods=['GET'])
def admin_profile_edit():

    if 'admin_id' not in session:
        flash("Please login!", "danger")
        return redirect('/admin-login')

    return render_template('admin/profile_edit.html')



@app.route('/admin-logout')
def admin_logout():

    # Clear admin session
    session.clear()

    flash("Logged out successfully.", "success")
    return redirect(url_for('admin_login'))


# =================================================================
# ROUTE: USER REGISTRATION
# =================================================================
@app.route('/user-register', methods=['GET', 'POST'])
def user_register():

    if request.method == 'GET':
        return render_template("user/user_register.html")

    # 🔹 Get form data (strip spaces)
    name = request.form['name'].strip()
    email = request.form['email'].strip().lower()
    password = request.form['password']
    phone = request.form['phone'].strip()
    address = request.form.get('address', '').strip()

    # =========================
    # 🔥 VALIDATIONS
    # =========================

    # ✅ Email validation
    email_pattern = r'^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$'
    if not re.match(email_pattern, email, re.IGNORECASE):
        flash("Invalid email format!", "danger")
        return redirect('/user-register')

    # ✅ Phone validation
    if len(phone) != 10 or not phone.isdigit():
        flash("Invalid phone number!", "danger")
        return redirect('/user-register')

    # ✅ Password strength
    if len(password) < 6:
        flash("Password must be at least 6 characters!", "danger")
        return redirect('/user-register')

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    # =========================
    # 🔥 CHECK EXISTING USER
    # =========================

    # Email check
    cursor.execute("SELECT * FROM users WHERE email=%s", (email,))
    if cursor.fetchone():
        flash("Email already registered. Please login.", "warning")
        return redirect('/user-register')

    # Phone check (IMPORTANT)
    cursor.execute("SELECT * FROM users WHERE phone=%s", (phone,))
    if cursor.fetchone():
        flash("Phone number already registered!", "warning")
        return redirect('/user-register')

    # =========================
    # 🔐 HASH PASSWORD
    # =========================
    hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())

    # =========================
    # 💾 INSERT USER
    # =========================
    cursor.execute(
        "INSERT INTO users (name, email, password, phone, address) VALUES (%s, %s, %s, %s, %s)",
        (name, email, hashed_password, phone, address)
    )

    conn.commit()
    cursor.close()
    conn.close()

    flash("Registration successful! Please login.", "success")
    return redirect(url_for('user_login'))

# =================================================================
# ROUTE: USER LOGIN
# =================================================================
@app.route('/user-login', methods=['GET', 'POST'])
def user_login():

    if request.method == 'GET':
        return render_template("user/user_login.html")

    email = request.form['email']
    password = request.form['password']

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute("SELECT * FROM users WHERE email=%s", (email,))
    user = cursor.fetchone()

    cursor.close()
    conn.close()

    if not user:
        flash("Email not found! Please register.", "danger")
        return redirect('/user-login')

    # Verify password
    if not bcrypt.checkpw(password.encode('utf-8'), user['password'].encode('utf-8')):
        flash("Incorrect password!", "danger")
        return redirect('/user-login')

    # Create user session
    session['user_id'] = user['user_id']
    session['user_name'] = user['name']
    session['user_email'] = user['email']

    flash("Login successful!", "success")
    return redirect(url_for('user_dashboard'))

# =================================================================
# ROUTE: USER DASHBOARD
# =================================================================
@app.route('/user-dashboard')
def user_dashboard():

    if 'user_id' not in session:
        flash("Please login to continue.", "warning")
        return redirect('/user-login')

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    # 🔥 Latest products
    cursor.execute("SELECT * FROM products ORDER BY product_id DESC LIMIT 8")
    products = cursor.fetchall()

    # 🔥 ADD THIS (IMPORTANT)
    cursor.execute("SELECT DISTINCT category FROM products")
    categories = cursor.fetchall()

    cursor.close()
    conn.close()

    return render_template(
        "user/user_home.html",
        user_name=session['user_name'],
        products=products,
        categories=categories   # 🔥 FIX
    )


# ROUTE: USER PRODUCT LISTING (SEARCH + FILTER)
# =================================================================
@app.route('/user/products')
def user_products():

    # Optional: restrict only logged-in users
    if 'user_id' not in session:
        flash("Please login to view products!", "danger")
        return redirect('/user-login')

    search = request.args.get('search', '')
    category_filter = request.args.get('category', '')

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    # Fetch categories for filter dropdown
    cursor.execute("SELECT DISTINCT category FROM products")
    categories = cursor.fetchall()

    # Build dynamic SQL
    query = "SELECT * FROM products WHERE 1=1"
    params = []

    if search:
        query += " AND name LIKE %s"
        params.append("%" + search + "%")

    if category_filter:
        query += " AND category = %s"
        params.append(category_filter)

    cursor.execute(query, params)
    products = cursor.fetchall()

    cursor.close()
    conn.close()

    return render_template(
        "user/user_products.html",
        products=products,
        categories=categories
    )


# =================================================================
# ROUTE: USER PRODUCT DETAILS PAGE
# =================================================================
@app.route('/user/product/<int:product_id>')
def user_product_details(product_id):

    if 'user_id' not in session:
        flash("Please login!", "danger")
        return redirect('/user-login')

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    # 🔥 Get main product
    cursor.execute("SELECT * FROM products WHERE product_id = %s", (product_id,))
    product = cursor.fetchone()

    if not product:
        cursor.close()
        conn.close()
        flash("Product not found!", "danger")
        return redirect('/user/products')

    # 🔥 Get related products (same category)
    cursor.execute("""
        SELECT * FROM products 
        WHERE category = %s AND product_id != %s
        LIMIT 4
    """, (product['category'], product_id))

    related_products = cursor.fetchall()

    cursor.close()
    conn.close()

    return render_template(
        "user/product_details.html",
        product=product,
        related_products=related_products
    )

# =================================================================
# ADD ITEM TO CART
# =================================================================
from flask import jsonify, request

@app.route('/user/add-to-cart/<int:product_id>')
def add_to_cart(product_id):

    if 'user_id' not in session:
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return jsonify({"status": "error", "message": "login required"}), 401
        return redirect('/user-login')

    user_id = session['user_id']

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    # 🔥 Check product exists
    cursor.execute("SELECT * FROM products WHERE product_id=%s", (product_id,))
    product = cursor.fetchone()

    # ✅ FIXED BLOCK
    if not product:
        cursor.close()
        conn.close()

        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return jsonify({"status": "error", "message": "product not found"}), 404

        flash("Product not found", "danger")
        return redirect('/user/products')

    # 🔥 Check if already in cart
    cursor.execute("""
        SELECT quantity FROM cart 
        WHERE user_id=%s AND product_id=%s
    """, (user_id, product_id))

    item = cursor.fetchone()

    if item:
        cursor.execute("""
            UPDATE cart 
            SET quantity = quantity + 1
            WHERE user_id=%s AND product_id=%s
        """, (user_id, product_id))
    else:
        cursor.execute("""
            INSERT INTO cart (user_id, product_id, quantity)
            VALUES (%s, %s, 1)
        """, (user_id, product_id))

    conn.commit()

    # 🔥 Better cart count (recommended)
    cursor.execute("SELECT SUM(quantity) as count FROM cart WHERE user_id=%s", (user_id,))
    result = cursor.fetchone()
    cart_count = result['count'] if result['count'] else 0

    cursor.close()
    conn.close()

    # 🔥 AJAX response
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        return jsonify({
            "status": "success",
            "message": "Item added to cart",
            "cart_count": cart_count
        })
    

    flash("Item added to cart!", "success")
    return redirect(request.referrer)
# =================================================================
# VIEW CART PAGE
# =================================================================
@app.route('/user/cart')
def user_cart():

    if 'user_id' not in session:
        return redirect('/user-login')

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute("""
        SELECT c.product_id, c.quantity,
               p.name, p.price, p.image
        FROM cart c
        JOIN products p ON c.product_id = p.product_id
        WHERE c.user_id=%s
    """, (session['user_id'],))

    cart_items = cursor.fetchall()

    # total calculation
    grand_total = 0
    for item in cart_items:
        grand_total += item['price'] * item['quantity']

    cursor.close()
    conn.close()

    return render_template(
        "user/cart.html",
        cart_items=cart_items,
        grand_total=grand_total
    )

from flask import request, jsonify, session

@app.route('/user/update-cart', methods=['POST'])
def update_cart():

    # 🔐 Check login
    if 'user_id' not in session:
        return jsonify({"status": "error", "message": "Login required"}), 401

    data = request.get_json()
    product_id = data.get('product_id')
    action = data.get('action')

    user_id = session['user_id']

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    # 🔍 Get current item
    cursor.execute("""
        SELECT c.quantity, p.price 
        FROM cart c
        JOIN products p ON c.product_id = p.product_id
        WHERE c.user_id=%s AND c.product_id=%s
    """, (user_id, product_id))

    item = cursor.fetchone()

    # ❌ Item not found
    if not item:
        cursor.close()
        conn.close()
        return jsonify({"status": "error", "message": "Item not found"})

    quantity = item['quantity']
    price = item['price']

    # =========================================================
    # 🔥 HANDLE ACTIONS
    # =========================================================

    # ➕ INCREASE
    if action == "increase":
        quantity += 1

        cursor.execute("""
            UPDATE cart SET quantity=%s 
            WHERE user_id=%s AND product_id=%s
        """, (quantity, user_id, product_id))


    # ➖ DECREASE
    elif action == "decrease":

        if quantity > 1:
            quantity -= 1

            cursor.execute("""
                UPDATE cart SET quantity=%s 
                WHERE user_id=%s AND product_id=%s
            """, (quantity, user_id, product_id))

        else:
            # 🔥 REMOVE ITEM WHEN QTY = 1
            cursor.execute("""
                DELETE FROM cart 
                WHERE user_id=%s AND product_id=%s
            """, (user_id, product_id))

            conn.commit()

            # 🔥 recalc total
            cursor.execute("""
                SELECT SUM(p.price * c.quantity) AS total
                FROM cart c
                JOIN products p ON c.product_id = p.product_id
                WHERE c.user_id=%s
            """, (user_id,))
            total = cursor.fetchone()['total'] or 0

            cursor.close()
            conn.close()

            return jsonify({
                "status": "success",
                "message": "Item removed from cart",
                "cart_total": total
            })


    # 🗑 REMOVE
    elif action == "remove":

        cursor.execute("""
            DELETE FROM cart 
            WHERE user_id=%s AND product_id=%s
        """, (user_id, product_id))

        conn.commit()

        # 🔥 recalc total
        cursor.execute("""
            SELECT SUM(p.price * c.quantity) AS total
            FROM cart c
            JOIN products p ON c.product_id = p.product_id
            WHERE c.user_id=%s
        """, (user_id,))
        total = cursor.fetchone()['total'] or 0

        cursor.close()
        conn.close()

        return jsonify({
            "status": "success",
            "message": "Item removed",
            "cart_total": total
        })

    # =========================================================
    # 💾 SAVE CHANGES
    # =========================================================
    conn.commit()

    # 💰 Calculate item total
    item_total = quantity * price

    # 💰 Calculate cart total
    cursor.execute("""
        SELECT SUM(p.price * c.quantity) AS total
        FROM cart c
        JOIN products p ON c.product_id = p.product_id
        WHERE c.user_id=%s
    """, (user_id,))
    total = cursor.fetchone()['total'] or 0

    cursor.close()
    conn.close()

    return jsonify({
        "status": "success",
        "message": "Cart updated",
        "quantity": quantity,
        "item_total": item_total,
        "cart_total": total
    })





# =================================================================
# REMOVE ITEM
# =================================================================
@app.route('/user/cart/remove/<int:product_id>')
def remove_from_cart(product_id):

    if 'user_id' not in session:
        flash("Please login!", "danger")
        return redirect('/user-login')

    user_id = session['user_id']

    conn = get_db_connection()
    cursor = conn.cursor()

    # 🔥 Delete item from DB cart
    cursor.execute("""
        DELETE FROM cart 
        WHERE user_id=%s AND product_id=%s
    """, (user_id, product_id))

    conn.commit()

    cursor.close()
    conn.close()

    flash("Item removed!", "success")
    return redirect('/user/cart')

# =================================================================
# ROUTE: CREATE RAZORPAY ORDER
# =================================================================

@app.route('/user/buy-now/<int:product_id>')
def buy_now(product_id):

    if 'user_id' not in session:
        return redirect('/user-login')

    user_id = session['user_id']

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    # 🔥 SAME LOGIC HERE
    cursor.execute("""
        SELECT * FROM cart WHERE user_id=%s AND product_id=%s
    """, (user_id, product_id))

    item = cursor.fetchone()

    if item:
        cursor.execute("""
            UPDATE cart SET quantity = quantity + 1
            WHERE user_id=%s AND product_id=%s
        """, (user_id, product_id))
    else:
        cursor.execute("""
            INSERT INTO cart (user_id, product_id, quantity)
            VALUES (%s, %s, 1)
        """, (user_id, product_id))

    conn.commit()

    cursor.close()
    conn.close()

    return redirect('/user/pay')

@app.route('/user/pay')
def user_pay():

    if 'user_id' not in session:
        flash("Please login!", "danger")
        return redirect('/user-login')

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute("""
        SELECT c.quantity, p.name, p.price
        FROM cart c
        JOIN products p ON c.product_id = p.product_id
        WHERE c.user_id = %s
    """, (session['user_id'],))

    cart_items = cursor.fetchall()

    if not cart_items:
        cursor.close()
        conn.close()
        return redirect('/user/products')

    total_amount = sum(item['price'] * item['quantity'] for item in cart_items)
    razorpay_amount = int(total_amount * 100)

    try:
        razorpay_order = razorpay_client.order.create({
            "amount": razorpay_amount,
            "currency": "INR",
            "payment_capture": "1"
        })
    except Exception as e:
        app.logger.error("Razorpay error: %s", str(e))
        flash("Payment service error. Try again.", "danger")
        return redirect('/user/cart')

    session['razorpay_order_id'] = razorpay_order['id']

    cursor.close()
    conn.close()

    return render_template(
        "user/payment.html",
        amount=total_amount,
        cart_items=cart_items,   # 🔥 THIS WAS MISSING
        key_id=config.RAZORPAY_KEY_ID,
        order_id=razorpay_order['id']
    )
# =================================================================
# TEMP SUCCESS PAGE (Verification in Day 13)
# =================================================================
@app.route('/payment-success')
def payment_success():

    order_id = request.args.get('order_id')

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    # 🔥 GET ORDER DETAILS
    cursor.execute("""
        SELECT * FROM orders WHERE order_id=%s
    """, (order_id,))
    order = cursor.fetchone()

    # 🔥 GET ORDER ITEMS
    cursor.execute("""
        SELECT oi.quantity, oi.price, p.name AS product_name
        FROM order_items oi
        JOIN products p ON oi.product_id = p.product_id
        WHERE oi.order_id=%s
    """, (order_id,))

    items = cursor.fetchall()

    cursor.close()
    conn.close()

    return render_template(
        "user/payment_success.html",
        order=order,
        items=items   # ✅ THIS IS IMPORTANT
    )

# ------------------------------
# Route: Verify Payment and Store Order
# ------------------------------
@app.route('/verify-payment', methods=['POST'])
def verify_payment():

    if 'user_id' not in session:
        flash("Please login to complete the payment.", "danger")
        return redirect('/user-login')

    # Razorpay data
    razorpay_payment_id = request.form.get('razorpay_payment_id')
    razorpay_order_id = request.form.get('razorpay_order_id')
    razorpay_signature = request.form.get('razorpay_signature')

    # Address data
    name = request.form.get('name')
    phone = request.form.get('phone')
    address = request.form.get('address')
    city = request.form.get('city')
    state = request.form.get('state')
    pincode = request.form.get('pincode')

    if not (razorpay_payment_id and razorpay_order_id and razorpay_signature):
        flash("Payment verification failed.", "danger")
        return redirect('/user/cart')

    payload = {
        'razorpay_order_id': razorpay_order_id,
        'razorpay_payment_id': razorpay_payment_id,
        'razorpay_signature': razorpay_signature
    }

    try:
        razorpay_client.utility.verify_payment_signature(payload)
    except Exception as e:
        app.logger.error("Razorpay verification failed: %s", str(e))
        
        flash("Payment verification failed.", "danger")
        return redirect('/user/cart')

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    user_id = session['user_id']

    # 🔥 FETCH CART FROM DATABASE
    cursor.execute("""
        SELECT c.product_id, c.quantity, p.price, p.name
        FROM cart c
        JOIN products p ON c.product_id = p.product_id
        WHERE c.user_id=%s
    """, (user_id,))

    cart_items = cursor.fetchall()

    if not cart_items:
        flash("Cart is empty.", "danger")
        return redirect('/user/products')

    try:
        # 🔥 CALCULATE TOTAL
        total_amount = 0
        for item in cart_items:
          price = item['price'] or 0
          quantity = item['quantity']
          total_amount += price * quantity

        # 🔥 INSERT ORDER
        cursor.execute("""
            INSERT INTO orders 
            (user_id, razorpay_order_id, razorpay_payment_id, amount, payment_status, order_status,
             name, phone, address, city, state, pincode)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s)
        """, (
            user_id,
            razorpay_order_id,
            razorpay_payment_id,
            total_amount,
            'paid',
            'Placed',   # ✅ fixed
            name,
            phone,
            address,
            city,
            state,
            pincode
        ))

        order_db_id = cursor.lastrowid

        # 🔥 INSERT ORDER ITEMS + UPDATE STOCK
        for item in cart_items:
           product_id = item['product_id']
           quantity = item['quantity']
           price = item['price'] or 0
           product_name = item['name']

        cursor.execute("""
                INSERT INTO order_items 
                (order_id, product_id, product_name, quantity, price)
                VALUES (%s, %s, %s, %s, %s)
        """, (order_db_id, product_id, product_name, quantity, price))

            # Reduce stock
        cursor.execute("""
                UPDATE products 
                SET stock = stock - %s 
                WHERE product_id = %s
        """, (quantity, product_id))

        # 🔥 CLEAR CART (IMPORTANT)
        cursor.execute("DELETE FROM cart WHERE user_id=%s", (user_id,))

        conn.commit()

        # Optional: clear razorpay session
        session.pop('razorpay_order_id', None)

        flash("Payment successful!", "success")
        return redirect(url_for('order_success', order_db_id=order_db_id))

    except Exception as e:
        conn.rollback()
        app.logger.error("Order error: %s", str(e))
        flash("Error saving order.", "danger")
        return redirect('/user/cart')

    finally:
        cursor.close()
        conn.close()

@app.route('/user/order-success/<int:order_db_id>')
def order_success(order_db_id):
    if 'user_id' not in session:
        flash("Please login!", "danger")
        return redirect('/user-login')

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute("SELECT * FROM orders WHERE order_id=%s AND user_id=%s", (order_db_id, session['user_id']))
    order = cursor.fetchone()

    cursor.execute("SELECT * FROM order_items WHERE order_id=%s", (order_db_id,))
    items = cursor.fetchall()

    cursor.close()
    conn.close()

    if not order:
        flash("Order not found.", "danger")
        return redirect('/user/products')

    return render_template("user/order_success.html", order=order, items=items)

@app.route('/user/my-orders')
def my_orders():

    if 'user_id' not in session:
        flash("Please login!", "danger")
        return redirect('/user-login')

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute("""
        SELECT * FROM orders 
        WHERE user_id = %s 
        ORDER BY order_id DESC
    """, (session['user_id'],))

    orders = cursor.fetchall()

    from datetime import timedelta

    for order in orders:

        # fallback status
        if not order.get('order_status'):
            order['order_status'] = 'Placed'

        # delivery date
        if order.get('created_at'):
            order['delivery_date'] = order['created_at'] + timedelta(days=3)

        # get items
        cursor.execute("""
            SELECT oi.*, p.image 
            FROM order_items oi
            JOIN products p ON oi.product_id = p.product_id
            WHERE oi.order_id = %s
        """, (order['order_id'],))

        order['items'] = cursor.fetchall()

    cursor.close()
    conn.close()

    # ✅ THIS MUST EXIST (YOUR ERROR IS HERE)
    return render_template("user/my_orders.html", orders=orders)


@app.route('/user/track-order/<int:order_id>')
def track_order(order_id):

    if 'user_id' not in session:
        return redirect('/user-login')

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute("""
        SELECT * FROM orders 
        WHERE order_id=%s AND user_id=%s
    """, (order_id, session['user_id']))

    order = cursor.fetchone()

    if not order:
        flash("Order not found!", "danger")
        return redirect('/user/my-orders')

    # default tracking
    if not order.get('order_status'):
       order['order_status'] = 'Placed'

    print("DEBUG STATUS:", order['order_status'])

    cursor.close()
    conn.close()

    return render_template("user/track_order.html", order=order)


@app.route('/user/reorder/<int:order_id>')
def reorder(order_id):

    if 'user_id' not in session:
        flash("Please login!", "danger")
        return redirect('/user-login')

    user_id = session['user_id']

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    # 🔒 verify ownership
    cursor.execute("""
        SELECT * FROM orders 
        WHERE order_id=%s AND user_id=%s
    """, (order_id, user_id))

    order = cursor.fetchone()

    if not order:
        flash("Order not found!", "danger")
        return redirect('/user/my-orders')

    # 🔥 get order items
    cursor.execute("""
        SELECT product_id, quantity
        FROM order_items
        WHERE order_id=%s
    """, (order_id,))

    items = cursor.fetchall()

    # 🔥 insert/update into DB cart
    for item in items:
        product_id = item['product_id']
        quantity = item['quantity']

        # check if already in cart
        cursor.execute("""
            SELECT quantity FROM cart 
            WHERE user_id=%s AND product_id=%s
        """, (user_id, product_id))

        existing = cursor.fetchone()

        if existing:
            cursor.execute("""
                UPDATE cart 
                SET quantity = quantity + %s
                WHERE user_id=%s AND product_id=%s
            """, (quantity, user_id, product_id))
        else:
            cursor.execute("""
                INSERT INTO cart (user_id, product_id, quantity)
                VALUES (%s, %s, %s)
            """, (user_id, product_id, quantity))

    conn.commit()
    cursor.close()
    conn.close()

    flash("Items added to cart!", "success")
    return redirect('/user/cart')
# ----------------------------
# GENERATE INVOICE PDF
# ----------------------------
@app.route("/user/download-invoice/<int:order_id>")
def download_invoice(order_id):

    if 'user_id' not in session:
        flash("Please login!", "danger")
        return redirect('/user-login')

    # Fetch order
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute("SELECT * FROM orders WHERE order_id=%s AND user_id=%s",
                   (order_id, session['user_id']))
    order = cursor.fetchone()

    cursor.execute("SELECT * FROM order_items WHERE order_id=%s", (order_id,))
    items = cursor.fetchall()

    cursor.close()
    conn.close()

    if not order:
        flash("Order not found.", "danger")
        return redirect('/user/my-orders')

    # Render invoice HTML
    html = render_template("user/invoice.html", order=order, items=items)

    pdf = generate_pdf(html)
    if not pdf:
        flash("Error generating PDF", "danger")
        return redirect('/user/my-orders')

    # Prepare response
    response = make_response(pdf.getvalue())
    response.headers['Content-Type'] = 'application/pdf'
    response.headers['Content-Disposition'] = f"attachment; filename=invoice_{order_id}.pdf"

    return response

# ================================================================
# ADMIN: VIEW ALL ORDERS
# ================================================================
@app.route('/admin/orders')
def admin_orders():

    if 'admin_id' not in session:
        flash("Please login as admin!", "danger")
        return redirect('/admin-login')

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute("""
        SELECT o.order_id, o.user_id, o.amount, 
               o.payment_status, o.order_status, o.created_at,
               u.name AS username
        FROM orders o
        LEFT JOIN users u ON o.user_id = u.user_id
        ORDER BY o.created_at DESC
    """)

    orders = cursor.fetchall()
    cursor.close()
    conn.close()

    return render_template("admin/order_list.html", orders=orders)

# ================================================================
# ADMIN: VIEW ORDER DETAILS
# ================================================================
@app.route('/admin/order/<int:order_id>')
def admin_order_details(order_id):

    if 'admin_id' not in session:
        flash("Please login!", "danger")
        return redirect('/admin-login')

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute("SELECT * FROM orders WHERE order_id=%s", (order_id,))
    order = cursor.fetchone()

    cursor.execute("SELECT * FROM order_items WHERE order_id=%s", (order_id,))
    items = cursor.fetchall()

    cursor.close()
    conn.close()

    return render_template("admin/order_details.html", order=order, items=items)

# ================================================================
# ADMIN: UPDATE ORDER STATUS
# ================================================================
@app.route("/admin/update-order-status/<int:order_id>", methods=['POST'])
def update_order_status(order_id):
    if 'admin_id' not in session:
        flash("Please login!", "danger")
        return redirect('/admin-login')

    new_status = request.form.get('status')

    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute("UPDATE orders SET order_status=%s WHERE order_id=%s",
                    (new_status, order_id))

    conn.commit()
    cursor.close()
    conn.close()

    flash("Order status updated successfully!", "success")
    return redirect(f"/admin/order/{order_id}")




# =================================================================
# ROUTE: USER LOGOUT
# =================================================================
@app.route('/user-logout')
def user_logout():
    
    session.pop('user_id', None)
    session.pop('user_name', None)
    session.pop('user_email', None)

    flash("Logged out successfully!", "success")
    return redirect(url_for('home'))



    


def get_cart_count(user_id):
    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute("""
        SELECT SUM(quantity) AS count 
        FROM cart 
        WHERE user_id=%s
    """, (user_id,))

    result = cursor.fetchone()

    cursor.close()
    conn.close()

    return result['count'] if result['count'] else 0


@app.context_processor
def inject_cart_count():

    if 'user_id' in session:
        conn = get_db_connection()
        cursor = conn.cursor(dictionary=True)

        cursor.execute("""
            SELECT SUM(quantity) as count 
            FROM cart 
            WHERE user_id=%s
        """, (session['user_id'],))

        result = cursor.fetchone()
        cart_count = result['count'] if result['count'] else 0

        cursor.close()
        conn.close()

        return dict(cart_count=cart_count)

    return dict(cart_count=0)







# -------------------------------
# Run the Flask app
# -------------------------------
if __name__ == '__main__':
    app.run(debug=True)
